  version: 2
  
  jobs:
    build:
      docker:
        - image: meteor/circleci

      working_directory: ~/repo

      steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
        - run:
            name: Install meteor or run it
            command: meteor || curl https://install.meteor.com | /bin/sh
        - run:
            name: Install npm dependencies with meteor
            command: meteor npm install

        - save_cache:
            paths:
              - node_modules
              - .meteor
            key: v1-dependencies-{{ checksum "package.json" }}

        # run tests!
        - run: meteor test --once --driver-package meteortesting:mocha

    deploy: 
      docker:
        - image: meteor/circleci

      working_directory: ~/repo

      steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
        - run:
            name: Install now and meteor-now
            command: npm install -g meteor-now
        - run: 
            name: Now Login
            command: now --token NOW_TOKEN
        - run: 
            name: Now deploy
            command: meteor-now

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
