defaults: &defaults
  working_directory: ~/foster-test
  docker:
    - image: meteor/circleci

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install meteor or run it
          command: meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: Install npm dependencies with meteor
          command: meteor npm install

      - save_cache:
          paths:
            - node_modules
            - .meteor
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: meteor test --once --driver-package meteortesting:mocha

      - persist_to_workspace:
          root: ~/
          paths:
            - foster-test/*

  deploy_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install meteor or run it
          command: meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: Now deploy
          command: npm run deploy-dev

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
