defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: meteor/circleci

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install meteor or run it
          command: meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: Install npm dependencies with meteor
          command: meteor npm install

      - save_cache:
          paths:
            - node_modules
            - .meteor
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: meteor test --once --driver-package meteortesting:mocha

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/
      - run:
          name: Show working directory
          command: pwd
      - run:
          name: List
          command: ls -la
      - run:
          name: Install meteor or run it
          command: meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: Now deploy
          command: npm run deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
